---

- name: Update all current installed packages.
  yum:
    name: '*'
    state: latest
    

- name: Install libvirt and other related packages.
  package:
    name: "{{ kvm_packages }}"
    state: present
  notify: restart and enable libvirt.
